[package]
name = "json-fix"
version = "0.1.0"
edition = "2021"
description = "Robust JSON repair engine for fixing malformed or partial JSON strings, especially from AI output"
license = "MIT OR Apache-2.0"
repository = "https://github.com/MTraveller/json_fix" # <-- optional

[dependencies]
fancy-regex = "0.14"
serde_json = "1"